# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build test

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
          example:
            - 'pico_console_v2_midi'
            - 'pico_southbridge'
    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1

    - name: Checkout submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Configure CMake
      run: mkdir ${{github.workspace}}/${{matrix.example}}/build ;
           cd ${{github.workspace}}/${{matrix.example}}/build &&
           cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/${{matrix.example}}/build
      run: make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.example }}-build
        path: |
          ${{github.workspace}}/${{matrix.example}}/build/*.uf2
          ${{github.workspace}}/${{matrix.example}}/build/*.elf
          ${{github.workspace}}/${{matrix.example}}/build/*.bin
          ${{github.workspace}}/${{matrix.example}}/build/*.hex
        if-no-files-found: warn
        retention-days: 7
